### ISSUE TITLE
Problem with DataTable implementation

### ISSUE THREAD

**Issue by rafalciesielski** [takielias/tablar-kit#7]
Hello 
if I want to use the DataTable according to your tutorial , I get the message. I use the User model. 

<x-tabulator :table="$table"></x-tabulator>
Typed property Takielias\TablarKit\DataTable\DataTable::$columns must not be accessed before initialization

Could you add a usage example on GitHub ?

**Comment by takielias** [comment]
@rafalciesielski Did you check [DataTable Docs](https://tablar.ebuz.xyz/docs/4.0/datatable) ?

**Comment by rafalciesielski** [comment]
@takielias Yes, Is it possible to share demo source code ?

**Comment by takielias** [comment]
> @takielias Yes, Is it possible to share demo source code ?

Sure, I will share the demo source code soon.

**Comment by takielias** [comment]
@rafalciesielski You may check it : https://github.com/takielias/tablar-demo-project
